name: Client Workflow
on:
  push:
    branches: [dev]
    paths:
      - 'client/**'
  workflow_dispatch:
jobs:
  client:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: docker compose build
      - name: Test
        run: docker compose run --rm client npm run test
      - name: Cleanup
        if: always()
        run: docker compose down -v
